#ifndef STM32_MCS4_MEMORY_EMULATOR_PINS_H
#define STM32_MCS4_MEMORY_EMULATOR_PINS_H

#include "main.h"

// GPIO peripherals
#define PIN_PERIPHERAL_LED GPIOC

// GPIO pins
#define PIN_LED_DATA GPIO_PIN_12
#define PIN_LED_STAT GPIO_PIN_13

#endif //STM32_MCS4_MEMORY_EMULATOR_PINS_H
